"""English course (monolingual, beginner): 2 units, 6 skills, 12 lessons.

The UI is already in English, so this is not a translation course: prompts
teach vocabulary and grammar in English (emoji-to-word, opposites, correct
sentence, am/is/are, a/an, plurals, past tense, prepositions).
"""

from typing import Any

from app.content.builders import fb, mc, mp, ta, wb

PH = "Type in English"

UNITS: list[dict[str, Any]] = [
    {
        "title": "Basics",
        "description": "Say hello, name everyday things and use the verb “to be”.",
        "color": "#1C7ED6",
        "skills": [
            {
                "title": "Greetings & Introductions",
                "icon": "👋",
                "lessons": [
                    (
                        "Hello and goodbye",
                        [
                            mc("Which word do you say when you meet someone?",
                               ["Goodbye", "Hello", "Sorry", "Tomorrow"], "Hello",
                               "“Hello” is the everyday greeting. “Goodbye” is for leaving."),
                            mp([("Hello", "Goodbye"), ("Yes", "No"), ("Good", "Bad"), ("Arrive", "Leave")],
                               "Learning words in opposite pairs makes them easier to remember."),
                            fb("Choose the word that completes the sentence.", "Nice ___ meet you.",
                               ["for", "at", "to"], "to",
                               "The fixed phrase is “Nice to meet you.”"),
                            wb("Put the words in order: ask someone how they are.",
                               ["are", "you", "How", "is"], ["How are you?"],
                               "With “you”, always use “are”: How are you?"),
                            ta("Complete the reply: “Thank you!” — “You're ___!”",
                               ["welcome", "you're welcome", "you’re welcome"],
                               "“You're welcome” is the polite answer to “Thank you.”", PH),
                            mc("It's late and you are going to bed. What do you say to your family?",
                               ["Good morning.", "Good afternoon.", "Good night.", "Good evening."], "Good night.",
                               "“Good night” is for going to bed; “Good evening” is a greeting when you arrive."),
                        ],
                    ),
                    (
                        "What's your name?",
                        [
                            mc("Which sentence is correct?",
                               ["My name are Sam.", "Me name is Sam.", "I name is Sam.", "My name is Sam."],
                               "My name is Sam.", "Use “my” before a noun, and “is” with “name”."),
                            fb("Choose the right form of “to be”.", "I ___ from Brazil.", ["am", "is", "are"], "am",
                               "With “I”, always use “am”."),
                            wb("Put the words in order: ask someone their name.",
                               ["your", "name", "What", "is", "are"], ["What is your name?", "What's your name?"],
                               "“Name” is singular, so we use “is”: What is your name?"),
                            mp([("I", "my"), ("you", "your"), ("he", "his"), ("she", "her")],
                               "Possessive words show who something belongs to: my book, her bag."),
                            ta("Type the missing word: “Where are you ___?” (you want to know someone's home country)",
                               ["from", "Where are you from?"],
                               "“Where are you from?” asks about someone's country or city.", PH),
                            mc("Someone says “Nice to meet you.” What do you say?",
                               ["You're welcome.", "Nice to meet you too.", "Good night.", "I'm sorry."],
                               "Nice to meet you too.", "Add “too” to return the same kind words."),
                        ],
                    ),
                ],
            },
            {
                "title": "Everyday Words",
                "icon": "🍎",
                "lessons": [
                    (
                        "Things around us",
                        [
                            mc("Which word matches 🍎?", ["Banana", "Orange", "Apple", "Grape"], "Apple",
                               "🍎 is an apple."),
                            mp([("🐶", "dog"), ("🐱", "cat"), ("🏠", "house"), ("🚗", "car")],
                               "These are some of the most common English nouns."),
                            fb("Choose the right word.", "I have ___ umbrella.", ["a", "two", "an"], "an",
                               "Use “an” before a vowel sound: an umbrella, an apple."),
                            wb("Put the words in order: tell someone you have a pet.",
                               ["have", "dog", "I", "a", "an"], ["I have a dog."],
                               "“Dog” starts with a consonant sound, so we say “a dog”."),
                            ta("Type the plural of “box”.", ["boxes"],
                               "Words ending in -x, -s, -sh or -ch add -es: box → boxes.", PH),
                            mc("Which word matches 📚?", ["Books", "Pens", "Bags", "Chairs"], "Books",
                               "📚 shows a pile of books."),
                        ],
                    ),
                    (
                        "Colours and opposites",
                        [
                            mc("What is the opposite of “hot”?", ["Warm", "Cold", "Big", "Wet"], "Cold",
                               "Hot ↔ cold. “Warm” is only a little hot."),
                            fb("Choose the right word.", "I can see two ___.", ["cat", "cates", "cats"], "cats",
                               "Most nouns add -s in the plural: one cat, two cats."),
                            mp([("big", "small"), ("fast", "slow"), ("happy", "sad"), ("open", "closed")],
                               "Each word has an opposite. Learn them in pairs!"),
                            wb("Put the words in order: describe the colour of the sky.",
                               ["blue", "sky", "The", "is", "are"], ["The sky is blue."],
                               "“Sky” is singular, so we use “is”."),
                            ta("Type the opposite of “big”.", ["small", "little"],
                               "Big ↔ small (or little).", PH),
                            mc("Which word matches 🔴?", ["Green", "Yellow", "Blue", "Red"], "Red",
                               "🔴 is a red circle."),
                        ],
                    ),
                ],
            },
            {
                "title": "The Verb “to be”",
                "icon": "🧩",
                "lessons": [
                    (
                        "I am, you are",
                        [
                            fb("Choose the right form of “to be”.", "She ___ a doctor.", ["am", "are", "is"], "is",
                               "Use “is” with he, she and it."),
                            mc("Which sentence is correct?",
                               ["They is happy.", "They am happy.", "They are happy.", "They be happy."],
                               "They are happy.", "Use “are” with we, you and they."),
                            mp([("I am", "I'm"), ("you are", "you're"), ("she is", "she's"), ("they are", "they're")],
                               "In speech we usually use the short forms (contractions)."),
                            wb("Put the words in order: say that you are a student.",
                               ["student", "am", "I", "a", "is"], ["I am a student.", "I'm a student."],
                               "“I” always goes with “am”."),
                            ta("Type the short form (contraction) of “we are”.", ["we're", "we’re"],
                               "The apostrophe replaces the letter “a”: we are → we're.", PH),
                            mc("Which question is correct?",
                               ["Is you ready?", "Are you ready?", "Am you ready?", "Be you ready?"],
                               "Are you ready?", "In questions, “are” moves in front of “you”."),
                        ],
                    ),
                    (
                        "Negatives and questions",
                        [
                            mc("Which sentence is correct?",
                               ["He is not tired.", "He not is tired.", "He no is tired.", "He does not tired."],
                               "He is not tired.", "Put “not” after “is”: he is not (he isn't)."),
                            fb("Choose the right word.", "___ they at home?", ["Is", "Am", "Are"], "Are",
                               "Questions with “they” start with “Are”."),
                            wb("Put the words in order: ask where the bathroom is.",
                               ["the", "bathroom", "Where", "is", "are"],
                               ["Where is the bathroom?", "Where's the bathroom?"],
                               "“Bathroom” is singular, so we use “is”."),
                            mp([("is not", "isn't"), ("are not", "aren't"), ("I am not", "I'm not"), ("it is", "it's")],
                               "Contractions join two words with an apostrophe."),
                            ta("Type the short form (contraction) of “is not”.", ["isn't", "isn’t"],
                               "is not → isn't. The apostrophe replaces the “o”.", PH),
                            mc("Someone asks “Are you hungry?” Which answer is correct?",
                               ["Yes, I is.", "Yes, I are.", "Yes, am I.", "Yes, I am."], "Yes, I am.",
                               "Short answers repeat the verb: Yes, I am. / No, I'm not."),
                        ],
                    ),
                ],
            },
        ],
    },
    {
        "title": "Daily English",
        "description": "Shop for food, talk about your day and tell stories about the past.",
        "color": "#AE3EC9",
        "skills": [
            {
                "title": "Food & Shopping",
                "icon": "🛒",
                "lessons": [
                    (
                        "At the market",
                        [
                            mc("Which word matches 🥕?", ["Potato", "Carrot", "Onion", "Tomato"], "Carrot",
                               "🥕 is a carrot."),
                            mp([("🍞", "bread"), ("🧀", "cheese"), ("🥛", "milk"), ("🥚", "egg")],
                               "You can find all of these at the market."),
                            fb("Choose the right word.", "How ___ apples do you want?", ["much", "lot", "many"], "many",
                               "Use “many” with things you can count: how many apples?"),
                            wb("Put the words in order: ask the price of something.",
                               ["much", "does", "How", "this", "cost", "many"], ["How much does this cost?"],
                               "“How much” asks about price."),
                            ta("Type the plural of “tomato”.", ["tomatoes"],
                               "Some words ending in -o add -es: tomato → tomatoes.", PH),
                            mc("Which of these can you drink?", ["Bread", "Rice", "Juice", "Cheese"], "Juice",
                               "Juice is a drink; the others are foods you eat."),
                        ],
                    ),
                    (
                        "At the café",
                        [
                            mc("Which is the most polite way to order?",
                               ["Give me a coffee.", "I want coffee now.", "Coffee!", "Could I have a coffee, please?"],
                               "Could I have a coffee, please?", "“Could I have…, please?” is polite and friendly."),
                            fb("Choose the right form of “to be”.", "There ___ some milk in the fridge.",
                               ["are", "is", "am"], "is",
                               "“Milk” is uncountable, so we use “there is”."),
                            wb("Put the words in order: politely ask for water.",
                               ["have", "Can", "some", "I", "water", "please", "am"],
                               ["Can I have some water, please?", "Can I please have some water?",
                                "Please, can I have some water?"],
                               "“Can I have…?” is a simple, polite way to ask for something."),
                            mp([("potato", "potatoes"), ("knife", "knives"), ("glass", "glasses"), ("cherry", "cherries")],
                               "Watch the spelling: -o can add -es, -f(e) becomes -ves, and -y becomes -ies."),
                            ta("Type the plural of “sandwich”.", ["sandwiches"],
                               "Words ending in -ch add -es: sandwich → sandwiches.", PH),
                            mc("The waiter brings your food and says “Here you are.” What do you say?",
                               ["Thank you.", "You're welcome.", "Excuse me?", "Goodbye."], "Thank you.",
                               "Say “Thank you” when someone gives you something."),
                        ],
                    ),
                ],
            },
            {
                "title": "Daily Routine",
                "icon": "⏰",
                "lessons": [
                    (
                        "Every day",
                        [
                            fb("Choose the right word.", "She ___ up at seven every day.",
                               ["get", "gets", "getting"], "gets",
                               "With he, she and it, present simple verbs add -s."),
                            mc("Which sentence is correct?",
                               ["He go to work by bus.", "He goes to work by bus.", "He going to work by bus.",
                                "He gos to work by bus."],
                               "He goes to work by bus.", "“Go” becomes “goes” with he, she and it."),
                            wb("Put the words in order: say when you have breakfast.",
                               ["breakfast", "eight", "I", "at", "have", "in"],
                               ["I have breakfast at eight.", "At eight, I have breakfast."],
                               "Use “at” with clock times: at eight, at 7:30."),
                            mp([("🛏️", "sleep"), ("🚿", "shower"), ("🍳", "cook"), ("🏃", "run")],
                               "These verbs describe everyday activities."),
                            ta("Type the present-tense form of “watch”: “She ___ TV every evening.”", ["watches"],
                               "Verbs ending in -ch add -es with he, she and it: she watches.", PH),
                            mc("Which word matches ⏰?", ["Alarm clock", "Phone", "Lamp", "Door"], "Alarm clock",
                               "⏰ is an alarm clock. It wakes you up!"),
                        ],
                    ),
                    (
                        "Times and days",
                        [
                            mc("Which day comes after Monday?", ["Sunday", "Wednesday", "Tuesday", "Friday"],
                               "Tuesday", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday."),
                            fb("Choose the right preposition.", "My birthday is ___ July.", ["on", "in", "at"], "in",
                               "Use “in” with months and years: in July, in 2024."),
                            mp([("early", "late"), ("morning", "evening"), ("first", "last"), ("start", "finish")],
                               "Opposite pairs help you talk about time."),
                            wb("Put the words in order: ask someone what time it is.",
                               ["time", "is", "What", "it", "are"], ["What time is it?"],
                               "In questions, “is” comes before “it”."),
                            ta("Type the day that comes before Saturday.", ["Friday"],
                               "Friday comes just before the weekend.", PH),
                            mc("Which sentence is correct?",
                               ["I play football in Sundays.", "I play football at Sundays.",
                                "I play football by Sundays.", "I play football on Sundays."],
                               "I play football on Sundays.", "Use “on” with days: on Monday, on Sundays."),
                        ],
                    ),
                ],
            },
            {
                "title": "Talking About the Past",
                "icon": "🕰️",
                "lessons": [
                    (
                        "Yesterday",
                        [
                            mc("Which sentence is correct?",
                               ["Yesterday I walked to school.", "Yesterday I walk to school.",
                                "Yesterday I walking to school.", "Yesterday I walks to school."],
                               "Yesterday I walked to school.", "Regular verbs add -ed in the past: walk → walked."),
                            fb("Choose the right word.", "We ___ a film last night.",
                               ["watch", "watching", "watched"], "watched",
                               "“Last night” is in the past, so use the past tense."),
                            mp([("play", "played"), ("go", "went"), ("eat", "ate"), ("see", "saw")],
                               "“Play” is regular (-ed); go, eat and see are irregular."),
                            wb("Put the words in order: say what you did last weekend.",
                               ["visited", "my", "I", "grandmother", "visit"], ["I visited my grandmother."],
                               "Use the past tense “visited” for a finished action."),
                            ta("Type the past tense of “go”.", ["went"],
                               "“Go” is irregular: go → went.", PH),
                            mc("Which word is the past tense of “stop”?",
                               ["Stoped", "Stops", "Stopping", "Stopped"], "Stopped",
                               "Double the final consonant before -ed: stop → stopped."),
                        ],
                    ),
                    (
                        "Did you...?",
                        [
                            fb("Choose the right word.", "___ you see the game yesterday?",
                               ["Do", "Did", "Does"], "Did",
                               "Past questions start with “Did”."),
                            mc("Which question is correct?",
                               ["Did she went home?", "Did she go home?", "Does she went home?", "Did she goes home?"],
                               "Did she go home?", "After “did”, use the base verb: did she go?"),
                            wb("Put the words in order: say that you did not like the film.",
                               ["like", "did", "I", "film", "the", "not", "liked"],
                               ["I did not like the film.", "I didn't like the film."],
                               "After “did not”, use the base verb “like”, not “liked”."),
                            mp([("buy", "bought"), ("write", "wrote"), ("take", "took"), ("make", "made")],
                               "These common verbs are irregular in the past."),
                            ta("Type the past tense of “have”.", ["had"],
                               "“Have” is irregular: have → had.", PH),
                            mc("Choose the correct sentence about yesterday.",
                               ["They was tired yesterday.", "They are tired yesterday.",
                                "They were tired yesterday.", "They be tired yesterday."],
                               "They were tired yesterday.", "Use “were” with we, you and they in the past."),
                        ],
                    ),
                ],
            },
        ],
    },
]

COURSE: dict[str, Any] = {
    "title": "English",
    "language_code": "en",
    "flag_emoji": "🇬🇧",
    "description": "Beginner English: greetings, everyday words, “to be”, food, routines and the past.",
    "units": UNITS,
}
