"""French course (from English): 2 units, 6 skills, 12 lessons."""

from typing import Any

from app.content.builders import fb, mc, mp, ta, wb

PH = "Type in French"

UNITS: list[dict[str, Any]] = [
    {
        "title": "Basics",
        "description": "Say hello, introduce yourself and learn everyday words.",
        "color": "#2563EB",
        "skills": [
            {
                "title": "Greetings",
                "icon": "👋",
                "lessons": [
                    (
                        "Hello and goodbye",
                        [
                            mc("Which one means “hello”?", ["Merci", "Au revoir", "Bonjour", "S'il vous plaît"],
                               "Bonjour", "“Bonjour” literally means “good day” and works until the evening."),
                            mp([("Bonjour", "Hello"), ("Au revoir", "Goodbye"), ("Merci", "Thank you"),
                                ("Bonne nuit", "Good night")],
                               "These four words cover most everyday greetings."),
                            wb("Translate: “Hello, sir”", ["monsieur", "Merci", "Bonjour", "madame"],
                               ["Bonjour, monsieur"],
                               "Adding “monsieur” or “madame” to “bonjour” is polite in France."),
                            fb("Fill in the blank: “Good night, Marie!”", "Bonne ___, Marie !",
                               ["soir", "nuit", "jour"], "nuit",
                               "“Nuit” is feminine, so it's “bonne nuit”; “soir” and “jour” are masculine."),
                            ta("Type this in French: “Goodbye”", ["Au revoir", "Salut"],
                               "“Au revoir” means goodbye; “salut” is a casual hi or bye between friends.", PH),
                            mc("How do you say “see you later”?",
                               ["Bonne nuit", "À plus tard", "Enchanté", "De rien"], "À plus tard",
                               "“À plus tard” literally means “until later”; friends shorten it to “à plus”."),
                        ],
                    ),
                    (
                        "How are you?",
                        [
                            mc("What does “Comment ça va ?” mean?",
                               ["What is your name?", "Where are you going?", "How old are you?", "How are you?"],
                               "How are you?", "“Comment ça va ?” is the everyday, informal way to ask how someone is."),
                            fb("Fill in the blank: “I'm fine, thank you.”", "Je vais ___, merci.",
                               ["bon", "bien", "bonne"], "bien",
                               "Use the adverb “bien” (well) with “aller”: je vais bien."),
                            wb("Translate: “Good night, see you tomorrow”",
                               ["à", "soir", "Bonne", "demain", "nuit", "bonjour"],
                               ["Bonne nuit, à demain"],
                               "“À demain” means “until tomorrow”."),
                            mp([("Bien", "Well"), ("Mal", "Badly"), ("Très", "Very"), ("Demain", "Tomorrow")],
                               "“Très bien” means “very well”."),
                            ta("Type this in French: “Thank you very much”", ["Merci beaucoup", "Merci bien"],
                               "“Beaucoup” means “a lot”: merci beaucoup.", PH),
                            mc("Someone says “Merci.” How do you reply?",
                               ["De rien", "S'il te plaît", "Salut", "Pardon"], "De rien",
                               "“De rien” means “you're welcome” (literally “it's nothing”)."),
                        ],
                    ),
                ],
            },
            {
                "title": "Introductions",
                "icon": "🙋",
                "lessons": [
                    (
                        "What's your name?",
                        [
                            mc("How do you ask “What is your name?”",
                               ["Comment ça va ?", "Où habites-tu ?", "Comment tu t'appelles ?", "Tu as quel âge ?"],
                               "Comment tu t'appelles ?",
                               "“Comment tu t'appelles ?” literally means “How do you call yourself?”"),
                            fb("Fill in the blank: “My name is Léa.”", "Je m'___ Léa.",
                               ["appelles", "appeler", "appelle"], "appelle",
                               "With “je”, the verb is “appelle”: je m'appelle = I call myself."),
                            wb("Translate: “My name is Paul”", ["Paul", "t'appelles", "Je", "m'appelle", "Tu"],
                               ["Je m'appelle Paul"],
                               "“Me” becomes “m'” before a vowel: je m'appelle."),
                            mp([("Je", "I"), ("Tu", "You"), ("Il", "He"), ("Elle", "She")],
                               "“Tu” is the informal “you”, for friends and family."),
                            ta("Type this in French: “Nice to meet you”",
                               ["Enchanté", "Enchantée", "Ravi de te rencontrer", "Ravie de te rencontrer",
                                "Ravi de vous rencontrer", "Ravie de vous rencontrer"],
                               "Say “enchanté” if you're male and “enchantée” if you're female.", PH),
                            mc("What does “Je suis de Paris” mean?",
                               ["I live in Paris", "I am from Paris", "I like Paris", "I am going to Paris"],
                               "I am from Paris", "“Être de” + a city tells where someone is from."),
                        ],
                    ),
                    (
                        "Where are you from?",
                        [
                            mc("How do you ask “Where are you from?”",
                               ["D'où viens-tu ?", "Où es-tu ?", "Où vas-tu ?", "Qui es-tu ?"],
                               "D'où viens-tu ?", "“D'où viens-tu ?” literally means “From where do you come?”"),
                            fb("Fill in the blank: “She is French.”", "Elle est ___.",
                               ["français", "françaises", "française"], "française",
                               "Adjectives agree with the subject: elle → française (feminine singular)."),
                            wb("Translate: “I am a student”", ["étudiant", "suis", "es", "Je", "ai"],
                               ["Je suis étudiant", "Je suis étudiante"],
                               "French drops the article with jobs and studies: je suis étudiant."),
                            mp([("Anglais", "English"), ("Français", "French"), ("Espagnol", "Spanish"),
                                ("Allemand", "German")],
                               "Inside a sentence, nationalities are lowercase in French: il est anglais."),
                            ta("Type this in French: “I am from London”", ["Je suis de Londres", "Je viens de Londres"],
                               "London is “Londres” in French.", PH),
                            mc("Choose the correct translation of “We are friends.”",
                               ["Nous avons amis", "Je suis ami", "Vous êtes amis", "Nous sommes amis"],
                               "Nous sommes amis", "“Sommes” is the “nous” form of “être”."),
                        ],
                    ),
                ],
            },
            {
                "title": "Everyday Words",
                "icon": "💬",
                "lessons": [
                    (
                        "Yes, no, please",
                        [
                            mc("Which one means “please”?", ["Merci", "Pardon", "De rien", "S'il vous plaît"],
                               "S'il vous plaît", "“S'il vous plaît” is polite; with friends, say “s'il te plaît”."),
                            mp([("Oui", "Yes"), ("Non", "No"), ("Aussi", "Also"), ("Toujours", "Always")],
                               "“Toujours” means always, and it can also mean “still”."),
                            fb("Fill in the blank: “Excuse me, where is the bathroom?”",
                               "Excusez-moi, où ___ les toilettes ?", ["est", "sont", "suis"], "sont",
                               "“Les toilettes” is plural in French, so the verb is “sont”."),
                            wb("Translate: “Yes, please”", ["plaît", "Non", "Oui", "merci", "vous", "s'il"],
                               ["Oui, s'il vous plaît", "Oui, s'il te plaît"],
                               "“S'il vous plaît” literally means “if it pleases you”."),
                            ta("Type this in French: “I'm sorry”",
                               ["Je suis désolé", "Je suis désolée", "Désolé", "Désolée", "Pardon"],
                               "Use “désolé” if you're male and “désolée” if you're female.", PH),
                            mc("What does “Je ne sais pas” mean?",
                               ["I'm not hungry", "I'm leaving", "I don't know", "I can't come"], "I don't know",
                               "“Savoir” means to know; “ne… pas” wraps the verb to make it negative."),
                        ],
                    ),
                    (
                        "Little words",
                        [
                            mc("Which one means “today”?", ["Demain", "Aujourd'hui", "Hier", "Maintenant"],
                               "Aujourd'hui", "“Aujourd'hui” means today; “demain” means tomorrow."),
                            fb("Fill in the blank: “I don't understand.”", "Je ne ___ pas.",
                               ["comprend", "comprendre", "comprends"], "comprends",
                               "“Comprends” (with an “s”) is the “je” form of “comprendre”."),
                            mp([("Aujourd'hui", "Today"), ("Hier", "Yesterday"), ("Maintenant", "Now"),
                                ("Ici", "Here")],
                               "“Aujourd'hui” is a single word with an apostrophe inside."),
                            wb("Translate: “I speak a little French”",
                               ["français", "peu", "Je", "anglais", "un", "parle", "beaucoup"],
                               ["Je parle un peu français", "Je parle un peu le français"],
                               "“Un peu” means “a little”."),
                            ta("Type this in French: “Do you speak English?”",
                               ["Tu parles anglais ?", "Parles-tu anglais ?", "Vous parlez anglais ?",
                                "Parlez-vous anglais ?", "Est-ce que tu parles anglais ?",
                                "Est-ce que vous parlez anglais ?"],
                               "Languages are lowercase in French: anglais, français.", PH),
                            mc("What does “Pas maintenant” mean?", ["Not now", "Not here", "Not today", "Never"],
                               "Not now", "“Pas” on its own can negate a word: pas maintenant = not now."),
                        ],
                    ),
                ],
            },
        ],
    },
    {
        "title": "Café & Travel",
        "description": "Order food and drinks and find your way around town.",
        "color": "#D6336C",
        "skills": [
            {
                "title": "Food & Drinks",
                "icon": "🥐",
                "lessons": [
                    (
                        "Bread and cheese",
                        [
                            mc("Which one means “bread”?", ["Le fromage", "La pomme", "Le beurre", "Le pain"],
                               "Le pain", "“Pain” is masculine: le pain."),
                            mp([("Le fromage", "Cheese"), ("La pomme", "Apple"), ("L'œuf", "Egg"),
                                ("Le poisson", "Fish")],
                               "“Pomme” is feminine; the other three are masculine."),
                            fb("Fill in the blank: “I eat an apple.”", "Je ___ une pomme.",
                               ["manges", "mange", "manger"], "mange",
                               "“Mange” is the “je” form of “manger” (to eat)."),
                            wb("Translate: “The bread is good”", ["bon", "pain", "La", "est", "Le", "bonne"],
                               ["Le pain est bon"],
                               "“Pain” is masculine, so the adjective is “bon”."),
                            ta("Type this in French: “the cheese”", ["Le fromage", "Fromage"],
                               "“Fromage” is masculine: le fromage.", PH),
                            mc("What does “J'aime les fruits” mean?",
                               ["I want fruit", "I buy fruit", "I like fruit", "I have fruit"], "I like fruit",
                               "“J'aime” is “je aime” with elision; it means “I like” or “I love”."),
                        ],
                    ),
                    (
                        "Something to drink",
                        [
                            mc("Which one means “water”?", ["Le lait", "L'eau", "Le jus", "Le vin"], "L'eau",
                               "“Eau” is feminine, but “la” becomes “l'” before a vowel: l'eau."),
                            fb("Fill in the blank: “We are thirsty.”", "Nous ___ soif.",
                               ["sommes", "avez", "avons"], "avons",
                               "French says “we have thirst”: nous avons soif."),
                            mp([("Le café", "Coffee"), ("Le thé", "Tea"), ("Le lait", "Milk"), ("Le jus", "Juice")],
                               "“Thé” (tea) has an accent on the “e”."),
                            wb("Translate: “Water, please”", ["l'eau", "plaît", "De", "s'il", "vous", "lait", "merci"],
                               ["De l'eau, s'il vous plaît", "L'eau, s'il vous plaît"],
                               "“De l'eau” means “some water”; French usually needs an article before food and drink."),
                            ta("Type this in French: “I'm hungry”", ["J'ai faim"],
                               "Like thirst, hunger uses “avoir”: j'ai faim.", PH),
                            mc("What does “Tu veux un thé ?” mean?",
                               ["Do you have tea?", "Is the tea hot?", "Do you like tea?", "Do you want a tea?"],
                               "Do you want a tea?", "“Veux” is the “tu” form of “vouloir” (to want)."),
                        ],
                    ),
                ],
            },
            {
                "title": "At the Café",
                "icon": "☕",
                "lessons": [
                    (
                        "Ordering",
                        [
                            mc("How do you ask for the menu?",
                               ["L'addition, s'il vous plaît", "Une table, s'il vous plaît",
                                "La carte, s'il vous plaît", "Les toilettes, s'il vous plaît"],
                               "La carte, s'il vous plaît",
                               "In a French restaurant the menu is “la carte”; “le menu” is often a set meal."),
                            fb("Fill in the blank: “I would like a coffee.”", "Je ___ un café.",
                               ["voudrais", "voudrait", "vouloir"], "voudrais",
                               "“Je voudrais” (I would like) is the polite way to order."),
                            mp([("L'addition", "Bill"), ("Le serveur", "Waiter"), ("La table", "Table"),
                                ("Le sucre", "Sugar")],
                               "“L'addition” is the bill at a café or restaurant."),
                            wb("Translate: “The bill, please”", ["plaît", "L'addition", "La", "vous", "carte", "s'il"],
                               ["L'addition, s'il vous plaît"],
                               "“Addition” starts with a vowel, so “la” becomes “l'”."),
                            ta("Type this in French: “A table for two, please”",
                               ["Une table pour deux, s'il vous plaît", "Une table pour deux personnes, s'il vous plaît",
                                "Table pour deux, s'il vous plaît", "Une table pour deux"],
                               "“Pour deux” means “for two”.", PH),
                            mc("The waiter asks “Vous désirez ?” What does it mean?",
                               ["Are you ready?", "Where do you want to sit?", "How was it?", "What would you like?"],
                               "What would you like?",
                               "“Vous désirez ?” is a polite way for staff to ask what you'd like."),
                        ],
                    ),
                    (
                        "At the table",
                        [
                            mc("Which one means “delicious”?", ["Chaud", "Délicieux", "Cher", "Plein"], "Délicieux",
                               "“Délicieux” becomes “délicieuse” with feminine nouns."),
                            fb("Fill in the blank: “The soup is delicious.”", "La soupe est ___.",
                               ["délicieux", "délicieuses", "délicieuse"], "délicieuse",
                               "“Soupe” is feminine singular, so “délicieuse”."),
                            mp([("La fourchette", "Fork"), ("Le couteau", "Knife"), ("La cuillère", "Spoon"),
                                ("L'assiette", "Plate")],
                               "“Assiette” is feminine: une assiette."),
                            wb("Translate: “I would like the fish, please”",
                               ["poisson", "le", "voudrais", "Je", "plaît", "s'il", "vous", "la", "poulet"],
                               ["Je voudrais le poisson, s'il vous plaît"],
                               "“Poisson” is masculine: le poisson."),
                            ta("Type this in French: “Water without ice”",
                               ["De l'eau sans glaçons", "L'eau sans glaçons", "Eau sans glaçons",
                                "De l'eau sans glace", "Eau sans glace"],
                               "“Sans” means without; “un glaçon” is an ice cube.", PH),
                            mc("What does “Le service est compris ?” mean?",
                               ["Is service included?", "Is the table free?", "Is the kitchen open?",
                                "Is dessert ready?"], "Is service included?",
                               "In France, “service compris” means the service charge is already in the price."),
                        ],
                    ),
                ],
            },
            {
                "title": "Getting Around",
                "icon": "🚆",
                "lessons": [
                    (
                        "Around town",
                        [
                            mc("Which one means “the station”?", ["La gare", "La plage", "Le marché", "La banque"],
                               "La gare", "“La gare” is a train station; a metro stop is “une station”."),
                            mp([("Le marché", "Market"), ("La plage", "Beach"), ("Le musée", "Museum"),
                                ("La ville", "City")],
                               "Most words ending in -ée are feminine, but “le musée” is an exception."),
                            fb("Fill in the blank: “I'm going to the station.”", "Je vais ___ gare.",
                               ["au", "à la", "aux"], "à la",
                               "“Gare” is feminine, so “à la gare”; “au” is “à + le”."),
                            wb("Translate: “Where is the station?”", ["la", "est", "gare", "Où", "le", "sont"],
                               ["Où est la gare ?", "La gare est où ?"],
                               "“Où” (where) has a grave accent; “ou” without it means “or”."),
                            ta("Type this in French: “the beach”", ["La plage", "Plage"],
                               "“Plage” is feminine: la plage.", PH),
                            mc("What does “Je vais au marché” mean?",
                               ["I like the market", "I'm going to the market", "I'm at the market",
                                "I sell at the market"], "I'm going to the market",
                               "“Au” is “à + le”: je vais au marché."),
                        ],
                    ),
                    (
                        "Trains and directions",
                        [
                            mc("Which one means “to the left”?", ["À droite", "Tout droit", "À gauche", "À côté"],
                               "À gauche", "“Gauche” is left; “droite” is right."),
                            fb("Fill in the blank: “Turn right.”", "Tournez à ___.", ["droit", "droite", "droits"],
                               "droite", "“À droite” means to the right; “tout droit” means straight ahead."),
                            mp([("Le train", "Train"), ("Le billet", "Ticket"), ("Le quai", "Platform"),
                                ("Le départ", "Departure")],
                               "“Un billet” is a ticket, and also a banknote."),
                            wb("Translate: “A ticket for Lyon, please”",
                               ["pour", "billet", "Un", "Lyon", "s'il", "plaît", "vous", "de", "une"],
                               ["Un billet pour Lyon, s'il vous plaît"],
                               "“Pour” + a place tells where the ticket takes you."),
                            ta("Type this in French: “The train is late”",
                               ["Le train est en retard", "Le train a du retard"],
                               "“En retard” means late; “à l'heure” means on time.", PH),
                            mc("What does “Allez tout droit” mean?",
                               ["Turn around", "Go straight ahead", "Stop here", "Take the second left"],
                               "Go straight ahead",
                               "“Tout droit” means straight ahead; don't mix it up with “à droite”."),
                        ],
                    ),
                ],
            },
        ],
    },
]

COURSE: dict[str, Any] = {
    "title": "French",
    "language_code": "fr",
    "flag_emoji": "🇫🇷",
    "description": "From “Bonjour !” to ordering at a café and catching a train.",
    "units": UNITS,
}
