"""Punjabi (Gurmukhi) course (from English): 2 units, 6 skills, 12 lessons.

Learners may not read Gurmukhi yet, so Punjabi options carry a romanization in
parentheses, word-bank prompts give a romanized hint, and type-answer exercises
accept common romanized spellings as well as the Gurmukhi. ``normalize`` strips
the danda "।", so learners may type it or not.
"""

from itertools import product
from typing import Any

from app.content.builders import fb, mc, mp, ta, wb

TYPE_HINT = "Type in Punjabi (romanized is fine)"


def _roman(display: str, *parts: list[str], extra: tuple[str, ...] = ()) -> list[str]:
    """``display`` first (shown as the correct answer), then every spelling combination."""
    combos = [" ".join(words) for words in product(*parts)]
    return [display, *[c for c in combos if c != display.lower()], *extra]


UNITS: list[dict[str, Any]] = [
    {
        "title": "Basics",
        "description": "Greet people, introduce yourself and talk about your family.",
        "color": "#E06D10",
        "skills": [
            {
                "title": "Greetings",
                "icon": "👋",
                "lessons": [
                    (
                        "Hello and goodbye",
                        [
                            mc("Which one means “hello”?",
                               ["ਸਤ ਸ੍ਰੀ ਅਕਾਲ (sat sri akaal)", "ਧੰਨਵਾਦ (dhanvaad)",
                                "ਫਿਰ ਮਿਲਾਂਗੇ (phir milaange)", "ਨਹੀਂ (nahin)"],
                               "ਸਤ ਸ੍ਰੀ ਅਕਾਲ (sat sri akaal)",
                               "“ਸਤ ਸ੍ਰੀ ਅਕਾਲ” is the everyday Punjabi greeting, used for both hello and goodbye."),
                            mp([("ਸਤ ਸ੍ਰੀ ਅਕਾਲ (sat sri akaal)", "Hello"), ("ਧੰਨਵਾਦ (dhanvaad)", "Thank you"),
                                ("ਹਾਂ (haan)", "Yes"), ("ਨਹੀਂ (nahin)", "No")],
                               "These four words get you through most first conversations."),
                            wb("Translate: “See you again” (phir milaange)", ["ਮਿਲਾਂਗੇ", "ਹਾਂ", "ਫਿਰ", "ਧੰਨਵਾਦ"],
                               ["ਫਿਰ ਮਿਲਾਂਗੇ"],
                               "“ਫਿਰ ਮਿਲਾਂਗੇ” literally means “we will meet again”."),
                            fb("Fill in the blank: “Thank you, see you again!” (dhanvaad, phir ___!)",
                               "ਧੰਨਵਾਦ, ਫਿਰ ___!", ["ਮਿਲਾਂਗੇ (milaange)", "ਨਹੀਂ (nahin)", "ਹਾਂ (haan)"],
                               "ਮਿਲਾਂਗੇ (milaange)", "ਮਿਲਾਂਗੇ means “(we) will meet”."),
                            ta("Type this in Punjabi (romanized): “Thank you”",
                               ["dhanvaad", "dhanvad", "dhanwaad", "dhanwad", "dhannvaad", "dhannvad",
                                "dhannwaad", "dhannwad", "ਧੰਨਵਾਦ",
                                "shukriya", "shukria", "shukriyaa", "ਸ਼ੁਕਰੀਆ"],
                               "“ਧੰਨਵਾਦ” (dhanvaad) is thank you; the ੰ (tippi) doubles the ਨ: dhann-vaad. "
                               "ਸ਼ੁਕਰੀਆ (shukriya) is common too.",
                               TYPE_HINT),
                            mc("How do you say “see you again”?",
                               ["ਸਤ ਸ੍ਰੀ ਅਕਾਲ (sat sri akaal)", "ਫਿਰ ਮਿਲਾਂਗੇ (phir milaange)",
                                "ਕਿਰਪਾ ਕਰਕੇ (kirpa karke)", "ਮੈਂ ਠੀਕ ਹਾਂ (main theek haan)"],
                               "ਫਿਰ ਮਿਲਾਂਗੇ (phir milaange)",
                               "ਫਿਰ means “again” and ਮਿਲਾਂਗੇ means “(we) will meet”."),
                        ],
                    ),
                    (
                        "How are you?",
                        [
                            mc("What does “ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ? (tusi kiven ho?)” mean?",
                               ["What is your name?", "How are you?", "Where are you?", "Who are you?"],
                               "How are you?",
                               "ਕਿਵੇਂ means “how”; ਤੁਸੀਂ is the polite, respectful “you”."),
                            fb("Fill in the blank: “I am fine.” (main ___ haan)", "ਮੈਂ ___ ਹਾਂ।",
                               ["ਠੀਕ (theek)", "ਕਿਵੇਂ (kiven)", "ਧੰਨਵਾਦ (dhanvaad)"], "ਠੀਕ (theek)",
                               "ਠੀਕ means fine or okay. ਹਾਂ is “am” after ਮੈਂ (and also means “yes”)."),
                            wb("Translate: “I am fine, thank you” (main theek haan, dhanvaad)",
                               ["ਹਾਂ", "ਧੰਨਵਾਦ", "ਮੈਂ", "ਕਿਵੇਂ", "ਠੀਕ"],
                               ["ਮੈਂ ਠੀਕ ਹਾਂ, ਧੰਨਵਾਦ", "ਧੰਨਵਾਦ, ਮੈਂ ਠੀਕ ਹਾਂ"],
                               "Punjabi puts the verb last: ਮੈਂ (I) ਠੀਕ (fine) ਹਾਂ (am)."),
                            mp([("ਕਿਰਪਾ ਕਰਕੇ (kirpa karke)", "Please"), ("ਠੀਕ (theek)", "Fine"),
                                ("ਕਿਵੇਂ (kiven)", "How"), ("ਬਹੁਤ (bahut)", "Very")],
                               "ਬਹੁਤ ਬਹੁਤ ਧੰਨਵਾਦ means “thank you very much”."),
                            ta("Type this in Punjabi (romanized): “Please”",
                               _roman("kirpa karke", ["kirpa", "kirpaa", "kripa"], ["karke", "karkay", "kar ke"],
                                      extra=("ਕਿਰਪਾ ਕਰਕੇ",)),
                               "“ਕਿਰਪਾ ਕਰਕੇ” literally means “doing a kindness”.",
                               TYPE_HINT),
                            mc("Someone asks “ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?” How do you reply?",
                               ["ਫਿਰ ਮਿਲਾਂਗੇ (phir milaange)", "ਕਿਰਪਾ ਕਰਕੇ (kirpa karke)",
                                "ਮੈਂ ਠੀਕ ਹਾਂ (main theek haan)", "ਨਹੀਂ (nahin)"],
                               "ਮੈਂ ਠੀਕ ਹਾਂ (main theek haan)",
                               "“ਮੈਂ ਠੀਕ ਹਾਂ” means “I am fine”."),
                        ],
                    ),
                ],
            },
            {
                "title": "Introductions",
                "icon": "🙋",
                "lessons": [
                    (
                        "What's your name?",
                        [
                            mc("How do you ask “What is your name?”",
                               ["ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ? (tusi kiven ho?)", "ਤੁਹਾਡਾ ਨਾਮ ਕੀ ਹੈ? (tuhaada naam ki hai?)",
                                "ਤੁਸੀਂ ਕਿੱਥੋਂ ਹੋ? (tusi kitthon ho?)", "ਇਹ ਕੀ ਹੈ? (eh ki hai?)"],
                               "ਤੁਹਾਡਾ ਨਾਮ ਕੀ ਹੈ? (tuhaada naam ki hai?)",
                               "ਤੁਹਾਡਾ means “your” (polite) and ਕੀ means “what”."),
                            fb("Fill in the blank: “My name is Arjun.” (___ naam Arjun hai)", "___ ਨਾਮ ਅਰਜੁਨ ਹੈ।",
                               ["ਮੇਰੀ (meri)", "ਮੇਰਾ (mera)", "ਮੇਰੇ (mere)"], "ਮੇਰਾ (mera)",
                               "ਨਾਮ (name) is masculine, so “my” is ਮੇਰਾ."),
                            wb("Translate: “My name is Simran” (mera naam Simran hai)",
                               ["ਨਾਮ", "ਹੈ", "ਮੇਰੀ", "ਸਿਮਰਨ", "ਮੇਰਾ"],
                               ["ਮੇਰਾ ਨਾਮ ਸਿਮਰਨ ਹੈ"],
                               "“My” agrees with ਨਾਮ, not with the person: even Simran says ਮੇਰਾ ਨਾਮ."),
                            mp([("ਮੈਂ (main)", "I"), ("ਤੁਸੀਂ (tusi)", "You (polite)"), ("ਉਹ (uh)", "He / She"),
                                ("ਅਸੀਂ (asi)", "We")],
                               "ਉਹ covers both “he” and “she”; the verb endings show the gender."),
                            ta("Type this in Punjabi (romanized): “My name is Simran”",
                               _roman("mera naam Simran hai", ["mera"], ["naam", "nam", "naa", "naan"], ["simran"],
                                      ["hai", "hae", "ae", "e"],
                                      extra=("ਮੇਰਾ ਨਾਮ ਸਿਮਰਨ ਹੈ", "ਮੇਰਾ ਨਾਂ ਸਿਮਰਨ ਹੈ")),
                               "ਮੇਰਾ ਨਾਮ … ਹੈ is the standard pattern for “my name is …”.",
                               TYPE_HINT),
                            mc("What does “ਮੈਂ ਵਿਦਿਆਰਥੀ ਹਾਂ (main vidiaarthi haan)” mean?",
                               ["I am a teacher", "I am a student", "You are a student", "I am from Punjab"],
                               "I am a student",
                               "ਵਿਦਿਆਰਥੀ means student; ਹਾਂ is “am” after ਮੈਂ."),
                        ],
                    ),
                    (
                        "Where are you from?",
                        [
                            mc("How do you ask “Where are you from?”",
                               ["ਤੁਸੀਂ ਕਿੱਥੇ ਹੋ? (tusi kitthe ho?)", "ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ? (tusi kiven ho?)",
                                "ਤੁਸੀਂ ਕਿੱਥੋਂ ਹੋ? (tusi kitthon ho?)", "ਤੁਹਾਡਾ ਨਾਮ ਕੀ ਹੈ? (tuhaada naam ki hai?)"],
                               "ਤੁਸੀਂ ਕਿੱਥੋਂ ਹੋ? (tusi kitthon ho?)",
                               "ਕਿੱਥੋਂ means “from where”; ਕਿੱਥੇ just means “where”."),
                            fb("Fill in the blank: “I am from Punjab.” (main Punjab ___ haan)", "ਮੈਂ ਪੰਜਾਬ ___ ਹਾਂ।",
                               ["ਤੋਂ (ton)", "ਵਿੱਚ (vich)", "ਨੂੰ (nu)"], "ਤੋਂ (ton)",
                               "ਤੋਂ means “from” and comes after the place; ਵਿੱਚ would mean “in”."),
                            wb("Translate: “We are from India” (asi Bharat ton haan)",
                               ["ਤੋਂ", "ਹਾਂ", "ਅਸੀਂ", "ਹੋ", "ਭਾਰਤ"],
                               ["ਅਸੀਂ ਭਾਰਤ ਤੋਂ ਹਾਂ"],
                               "ਅਸੀਂ (we) also takes ਹਾਂ; ਹੋ goes with ਤੁਸੀਂ."),
                            mp([("ਮੈਂ ਹਾਂ (main haan)", "I am"), ("ਤੁਸੀਂ ਹੋ (tusi ho)", "You are"),
                                ("ਉਹ ਹੈ (uh hai)", "He / She is"), ("ਅਸੀਂ ਹਾਂ (asi haan)", "We are")],
                               "The verb “to be” changes with the pronoun: ਹਾਂ, ਹੋ, ਹੈ."),
                            ta("Type this in Punjabi (romanized): “Where are you from?”",
                               _roman("tusi kitthon ho", ["tusi", "tussi", "tusin", "tuseen"],
                                      ["kitthon", "kithon", "kittho", "kitho", "kithoon"], ["ho"],
                                      extra=("ਤੁਸੀਂ ਕਿੱਥੋਂ ਹੋ?",)),
                               "ਤੁਸੀਂ ਕਿੱਥੋਂ ਹੋ? — the ੱ (addak) doubles the “th” sound in ਕਿੱਥੋਂ.",
                               TYPE_HINT),
                            mc("Choose the correct translation of “She is from Canada.”",
                               ["ਉਹ ਕੈਨੇਡਾ ਤੋਂ ਹਾਂ (uh Canada ton haan)", "ਮੈਂ ਕੈਨੇਡਾ ਤੋਂ ਹਾਂ (main Canada ton haan)",
                                "ਉਹ ਕੈਨੇਡਾ ਤੋਂ ਹੈ (uh Canada ton hai)", "ਉਹ ਕੈਨੇਡਾ ਵਿੱਚ ਹੈ (uh Canada vich hai)"],
                               "ਉਹ ਕੈਨੇਡਾ ਤੋਂ ਹੈ (uh Canada ton hai)",
                               "ਉਹ takes ਹੈ; ਵਿੱਚ would mean “in Canada”, not “from”."),
                        ],
                    ),
                ],
            },
            {
                "title": "Family",
                "icon": "👪",
                "lessons": [
                    (
                        "My family",
                        [
                            mc("Which one means “mother”?",
                               ["ਭੈਣ (bhain)", "ਮਾਂ (maa)", "ਦਾਦੀ (daadi)", "ਪਿਤਾ (pita)"], "ਮਾਂ (maa)",
                               "ਮਾਂ is mother; the ਂ (bindi) makes the vowel nasal."),
                            mp([("ਮਾਂ (maa)", "Mother"), ("ਪਿਤਾ (pita)", "Father"), ("ਭਰਾ (bhra)", "Brother"),
                                ("ਭੈਣ (bhain)", "Sister")],
                               "The core family words."),
                            fb("Fill in the blank: “This is my sister.” (eh ___ bhain hai)", "ਇਹ ___ ਭੈਣ ਹੈ।",
                               ["ਮੇਰਾ (mera)", "ਮੇਰੀ (meri)", "ਮੇਰੇ (mere)"], "ਮੇਰੀ (meri)",
                               "ਭੈਣ is feminine, so “my” becomes ਮੇਰੀ."),
                            wb("Translate: “This is my brother” (eh mera bhra hai)",
                               ["ਭਰਾ", "ਮੇਰੀ", "ਇਹ", "ਹੈ", "ਮੇਰਾ"],
                               ["ਇਹ ਮੇਰਾ ਭਰਾ ਹੈ"],
                               "ਭਰਾ is masculine, so “my” is ਮੇਰਾ."),
                            ta("Type this in Punjabi (romanized): “Father”",
                               ["pita", "pita ji", "pitaji", "pio", "piyo", "bapu", "bapu ji", "baapu", "baapu ji",
                                "papa", "papa ji", "ਪਿਤਾ", "ਪਿਤਾ ਜੀ", "ਪਿਓ", "ਪਿਉ", "ਬਾਪੂ", "ਬਾਪੂ ਜੀ", "ਪਾਪਾ",
                                "ਪਾਪਾ ਜੀ"],
                               "ਪਿਤਾ is standard; ਪਿਓ and ਬਾਪੂ are common at home. Add ਜੀ (ji) for respect.",
                               TYPE_HINT),
                            mc("How do you say “my mother”?",
                               ["ਮੇਰਾ ਮਾਂ (mera maa)", "ਮੇਰੀ ਮਾਂ (meri maa)", "ਤੁਹਾਡੀ ਮਾਂ (tuhaadi maa)",
                                "ਮੇਰਾ ਭਰਾ (mera bhra)"],
                               "ਮੇਰੀ ਮਾਂ (meri maa)",
                               "ਮਾਂ is feminine, so it's ਮੇਰੀ. ਤੁਹਾਡੀ means “your”."),
                        ],
                    ),
                    (
                        "Grandparents",
                        [
                            mc("Who is your “ਦਾਦੀ (daadi)”?",
                               ["Mother's mother", "Father's father", "Father's mother", "Mother's father"],
                               "Father's mother",
                               "Punjabi names each side: ਦਾਦਾ/ਦਾਦੀ are your father's parents, "
                               "ਨਾਨਾ/ਨਾਨੀ your mother's."),
                            fb("Fill in the blank: “This is my grandmother (father's mother).” (eh meri ___ hai)",
                               "ਇਹ ਮੇਰੀ ___ ਹੈ।", ["ਨਾਨੀ (naani)", "ਦਾਦਾ (daada)", "ਦਾਦੀ (daadi)"], "ਦਾਦੀ (daadi)",
                               "Father's side → ਦਾਦੀ; ਮੇਰੀ already tells you it's a woman."),
                            wb("Translate: “My grandfather (mother's father) is from Amritsar” "
                               "(mere naana ji Amritsar ton han)",
                               ["ਜੀ", "ਹਨ", "ਨਾਨਾ", "ਮੇਰੇ", "ਅੰਮ੍ਰਿਤਸਰ", "ਤੋਂ", "ਹੈ", "ਮੇਰਾ"],
                               ["ਮੇਰੇ ਨਾਨਾ ਜੀ ਅੰਮ੍ਰਿਤਸਰ ਤੋਂ ਹਨ", "ਮੇਰੇ ਨਾਨਾ ਅੰਮ੍ਰਿਤਸਰ ਤੋਂ ਹਨ",
                                "ਮੇਰਾ ਨਾਨਾ ਅੰਮ੍ਰਿਤਸਰ ਤੋਂ ਹੈ"],
                               "Elders get respect: add ਜੀ and use the plural ਮੇਰੇ … ਹਨ, even for one person."),
                            mp([("ਦਾਦਾ (daada)", "Father's father"), ("ਦਾਦੀ (daadi)", "Father's mother"),
                                ("ਨਾਨਾ (naana)", "Mother's father"), ("ਨਾਨੀ (naani)", "Mother's mother")],
                               "ਦ- words are dad's side, ਨ- words are mum's side."),
                            ta("Type this in Punjabi (romanized): “Grandmother (mother's mother)”",
                               ["naani", "nani", "naani ji", "nani ji", "ਨਾਨੀ", "ਨਾਨੀ ਜੀ"],
                               "ਨਾਨੀ is your mother's mother; ਨਾਨੀ ਜੀ is the respectful form.",
                               TYPE_HINT),
                            mc("How do you say “my brother and my sister”?",
                               ["ਮੇਰੀ ਭਰਾ ਤੇ ਮੇਰਾ ਭੈਣ (meri bhra te mera bhain)",
                                "ਮੇਰਾ ਭਰਾ ਤੇ ਮੇਰਾ ਭੈਣ (mera bhra te mera bhain)",
                                "ਮੇਰੀ ਭਰਾ ਤੇ ਮੇਰੀ ਭੈਣ (meri bhra te meri bhain)",
                                "ਮੇਰਾ ਭਰਾ ਤੇ ਮੇਰੀ ਭੈਣ (mera bhra te meri bhain)"],
                               "ਮੇਰਾ ਭਰਾ ਤੇ ਮੇਰੀ ਭੈਣ (mera bhra te meri bhain)",
                               "ਮੇਰਾ matches ਭਰਾ, ਮੇਰੀ matches ਭੈਣ. ਤੇ (short for ਅਤੇ) means “and”."),
                        ],
                    ),
                ],
            },
        ],
    },
    {
        "title": "Everyday Life",
        "description": "Order food and drink, count to ten and find your way around town.",
        "color": "#0E9384",
        "skills": [
            {
                "title": "Food & Drink",
                "icon": "🍲",
                "lessons": [
                    (
                        "Drinks",
                        [
                            mc("Which one means “water”?",
                               ["ਦੁੱਧ (duddh)", "ਚਾਹ (chaah)", "ਪਾਣੀ (paani)", "ਲੱਸੀ (lassi)"], "ਪਾਣੀ (paani)",
                               "ਪਾਣੀ is water — one of the most useful words anywhere."),
                            mp([("ਪਾਣੀ (paani)", "Water"), ("ਚਾਹ (chaah)", "Tea"), ("ਦੁੱਧ (duddh)", "Milk"),
                                ("ਲੱਸੀ (lassi)", "Yogurt drink")],
                               "Four drinks you'll be offered in any Punjabi home."),
                            fb("Fill in the blank: “The tea is hot.” (___ garam hai)", "___ ਗਰਮ ਹੈ।",
                               ["ਪਾਣੀ (paani)", "ਚਾਹ (chaah)", "ਦੁੱਧ (duddh)"], "ਚਾਹ (chaah)",
                               "ਚਾਹ is tea and ਗਰਮ means hot."),
                            wb("Translate: “Please give me water” (kirpa karke mainu paani dio)",
                               ["ਪਾਣੀ", "ਦਿਓ", "ਮੈਨੂੰ", "ਕਿਰਪਾ", "ਚਾਹ", "ਕਰਕੇ"],
                               ["ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੂੰ ਪਾਣੀ ਦਿਓ", "ਮੈਨੂੰ ਪਾਣੀ ਦਿਓ ਕਿਰਪਾ ਕਰਕੇ",
                                "ਕਿਰਪਾ ਕਰਕੇ ਪਾਣੀ ਦਿਓ"],
                               "ਮੈਨੂੰ means “to me” and ਦਿਓ is the polite “give”."),
                            ta("Type this in Punjabi (romanized): “Milk”",
                               ["duddh", "dudh", "doodh", "dudhh", "ਦੁੱਧ"],
                               "ਦੁੱਧ — the ੱ (addak) doubles the consonant after it.",
                               TYPE_HINT),
                            mc("What is “ਲੱਸੀ (lassi)”?",
                               ["Hot tea", "A yogurt drink", "Lentil soup", "Flatbread"], "A yogurt drink",
                               "ਲੱਸੀ is a chilled yogurt drink, sweet or salty — a Punjabi favourite."),
                        ],
                    ),
                    (
                        "A Punjabi meal",
                        [
                            mc("Which one means “flatbread”?",
                               ["ਦਾਲ (daal)", "ਸਬਜ਼ੀ (sabzi)", "ਰੋਟੀ (roti)", "ਪਾਣੀ (paani)"], "ਰੋਟੀ (roti)",
                               "ਰੋਟੀ is the everyday flatbread; it's also used to mean “a meal”."),
                            mp([("ਰੋਟੀ (roti)", "Flatbread"), ("ਦਾਲ (daal)", "Lentils"),
                                ("ਸਬਜ਼ੀ (sabzi)", "Vegetable dish"), ("ਚੌਲ (chaul)", "Rice")],
                               "Roti, daal, sabzi and rice make a classic Punjabi thali."),
                            fb("Fill in the blank: “I want water.” (mainu paani ___ hai)", "ਮੈਨੂੰ ਪਾਣੀ ___ ਹੈ।",
                               ["ਚਾਹੀਦੀ (chaahidi)", "ਚਾਹੀਦਾ (chaahida)", "ਚਾਹੀਦੇ (chaahide)"], "ਚਾਹੀਦਾ (chaahida)",
                               "With ਮੈਨੂੰ … ਚਾਹੀਦਾ, the verb agrees with the thing wanted: ਪਾਣੀ is masculine."),
                            wb("Translate: “I want tea” (mainu chaah chaahidi hai)",
                               ["ਚਾਹੀਦੀ", "ਹੈ", "ਮੈਨੂੰ", "ਚਾਹੀਦਾ", "ਚਾਹ"],
                               ["ਮੈਨੂੰ ਚਾਹ ਚਾਹੀਦੀ ਹੈ"],
                               "ਚਾਹ (tea) is feminine, so it's ਚਾਹੀਦੀ. Don't mix up ਚਾਹ and ਚਾਹੀਦੀ!"),
                            ta("Type this in Punjabi (romanized): “Vegetable dish”",
                               ["sabzi", "sabji", "sabzee", "sabjee", "subzi", "subji", "ਸਬਜ਼ੀ", "ਸਬਜੀ"],
                               "ਸਬਜ਼ੀ — the dot under ਜ਼ (nukta) turns “j” into “z”.",
                               TYPE_HINT),
                            mc("How do you say “The food is very good”?",
                               ["ਖਾਣਾ ਬਹੁਤ ਗਰਮ ਹੈ (khaana bahut garam hai)",
                                "ਪਾਣੀ ਬਹੁਤ ਵਧੀਆ ਹੈ (paani bahut vadhiya hai)",
                                "ਖਾਣਾ ਬਹੁਤ ਵਧੀਆ ਹੈ (khaana bahut vadhiya hai)",
                                "ਖਾਣਾ ਨਹੀਂ ਹੈ (khaana nahin hai)"],
                               "ਖਾਣਾ ਬਹੁਤ ਵਧੀਆ ਹੈ (khaana bahut vadhiya hai)",
                               "ਖਾਣਾ means food; ਵਧੀਆ (great) doesn't change for gender."),
                        ],
                    ),
                ],
            },
            {
                "title": "Numbers",
                "icon": "🔢",
                "lessons": [
                    (
                        "One to five",
                        [
                            mc("Which one means “three”?",
                               ["ਦੋ (do)", "ਤਿੰਨ (tinn)", "ਚਾਰ (chaar)", "ਪੰਜ (panj)"], "ਤਿੰਨ (tinn)",
                               "ਤਿੰਨ is three; the ੰ (tippi) adds the “n” sound."),
                            mp([("ਇੱਕ (ikk)", "One"), ("ਦੋ (do)", "Two"), ("ਚਾਰ (chaar)", "Four"),
                                ("ਪੰਜ (panj)", "Five")],
                               "Counting: ਇੱਕ, ਦੋ, ਤਿੰਨ, ਚਾਰ, ਪੰਜ."),
                            fb("Fill in the blank: “One, two, three” (ikk, ___, tinn)", "ਇੱਕ, ___, ਤਿੰਨ",
                               ["ਦਸ (das)", "ਛੇ (chhe)", "ਦੋ (do)"], "ਦੋ (do)",
                               "ਦੋ (two) comes between ਇੱਕ and ਤਿੰਨ."),
                            wb("Translate: “I have two brothers” (mere do bhra han)",
                               ["ਭਰਾ", "ਦੋ", "ਹੈ", "ਮੇਰੇ", "ਹਨ", "ਤਿੰਨ"],
                               ["ਮੇਰੇ ਦੋ ਭਰਾ ਹਨ"],
                               "For family, “I have” is ਮੇਰੇ … ਹਨ (“my … are”); both are plural here."),
                            ta("Type this in Punjabi (romanized): “Five”",
                               ["panj", "punj", "paanj", "ਪੰਜ"],
                               "ਪੰਜ gives Punjab its name: ਪੰਜ + ਆਬ, “five waters” (rivers).",
                               TYPE_HINT),
                            mc("What number is “ਚਾਰ (chaar)”?", ["2", "5", "4", "3"], "4",
                               "ਚਾਰ = 4. Gurmukhi also has its own digits: ੪ is 4."),
                        ],
                    ),
                    (
                        "Six to ten",
                        [
                            mc("Which one means “six”?",
                               ["ਸੱਤ (satt)", "ਛੇ (chhe)", "ਦਸ (das)", "ਦੋ (do)"], "ਛੇ (chhe)",
                               "ਛੇ is six — ਛ is an aspirated “ch”."),
                            mp([("ਸੱਤ (satt)", "Seven"), ("ਅੱਠ (atth)", "Eight"), ("ਨੌਂ (naun)", "Nine"),
                                ("ਦਸ (das)", "Ten")],
                               "ਸੱਤ, ਅੱਠ, ਨੌਂ, ਦਸ finish the count to ten."),
                            fb("Fill in the blank: “six, seven, eight” (chhe, satt, ___)", "ਛੇ, ਸੱਤ, ___",
                               ["ਦੋ (do)", "ਅੱਠ (atth)", "ਚਾਰ (chaar)"], "ਅੱਠ (atth)",
                               "ਅੱਠ (eight) follows ਸੱਤ (seven)."),
                            wb("Translate: “I have ten books” (mere kol das kitaabaan han)",
                               ["ਕਿਤਾਬਾਂ", "ਕੋਲ", "ਹਨ", "ਮੇਰੇ", "ਦਸ", "ਹੈ", "ਦੋ"],
                               ["ਮੇਰੇ ਕੋਲ ਦਸ ਕਿਤਾਬਾਂ ਹਨ"],
                               "ਮੇਰੇ ਕੋਲ literally means “near me” — the usual way to say “I have” for things."),
                            ta("Type this in Punjabi (romanized): “Nine”",
                               ["naun", "nau", "noun", "nou", "ਨੌਂ", "ਨੌ"],
                               "ਨੌਂ ends in a nasal sound, marked by the ਂ (bindi).",
                               TYPE_HINT),
                            mc("What is ਪੰਜ + ਪੰਜ (panj + panj)?",
                               ["ਨੌਂ (naun)", "ਅੱਠ (atth)", "ਦਸ (das)", "ਛੇ (chhe)"], "ਦਸ (das)",
                               "Five plus five is ਦਸ (ten)."),
                        ],
                    ),
                ],
            },
            {
                "title": "Around Town",
                "icon": "🏙️",
                "lessons": [
                    (
                        "Places",
                        [
                            mc("Which one means “home”?",
                               ["ਸਕੂਲ (skool)", "ਘਰ (ghar)", "ਬਜ਼ਾਰ (bazaar)", "ਹਸਪਤਾਲ (haspataal)"], "ਘਰ (ghar)",
                               "ਘਰ means both house and home."),
                            mp([("ਘਰ (ghar)", "Home"), ("ਬਜ਼ਾਰ (bazaar)", "Market"),
                                ("ਹਸਪਤਾਲ (haspataal)", "Hospital"), ("ਗੁਰਦੁਆਰਾ (gurdwara)", "Sikh temple")],
                               "Places you'll find in every Punjabi town."),
                            fb("Fill in the blank: “The market is far.” (bazaar ___ hai)", "ਬਜ਼ਾਰ ___ ਹੈ।",
                               ["ਕਿੱਥੇ (kitthe)", "ਦੂਰ (door)", "ਦਸ (das)"], "ਦੂਰ (door)",
                               "ਦੂਰ means far — it sounds like English “door”."),
                            wb("Translate: “This is my school” (eh mera skool hai)",
                               ["ਸਕੂਲ", "ਹੈ", "ਮੇਰੀ", "ਇਹ", "ਮੇਰਾ"],
                               ["ਇਹ ਮੇਰਾ ਸਕੂਲ ਹੈ"],
                               "ਸਕੂਲ is masculine, so “my” is ਮੇਰਾ."),
                            ta("Type this in Punjabi (romanized): “Hospital”",
                               ["haspataal", "haspatal", "hasptaal", "hasptal", "huspataal", "huspatal", "ਹਸਪਤਾਲ"],
                               "ਹਸਪਤਾਲ was borrowed from English “hospital”.",
                               TYPE_HINT),
                            mc("What is a “ਗੁਰਦੁਆਰਾ (gurdwara)”?",
                               ["A hospital", "A market", "A Sikh place of worship", "A school"],
                               "A Sikh place of worship",
                               "Every ਗੁਰਦੁਆਰਾ has a ਲੰਗਰ (langar), a free community kitchen open to all."),
                        ],
                    ),
                    (
                        "Where is it?",
                        [
                            mc("What does “ਕਿੱਥੇ ਹੈ? (kitthe hai?)” mean?",
                               ["What is it?", "Where is it?", "How is it?", "Who is it?"], "Where is it?",
                               "ਕਿੱਥੇ means “where”."),
                            fb("Fill in the blank: “Where is the market?” (bazaar ___ hai?)", "ਬਜ਼ਾਰ ___ ਹੈ?",
                               ["ਕਿੱਥੋਂ (kitthon)", "ਕਿਵੇਂ (kiven)", "ਕਿੱਥੇ (kitthe)"], "ਕਿੱਥੇ (kitthe)",
                               "ਕਿੱਥੇ = where; ਕਿੱਥੋਂ = from where."),
                            wb("Translate: “Where is the hospital?” (haspataal kitthe hai?)",
                               ["ਕਿੱਥੇ", "ਹਸਪਤਾਲ", "ਕਿਵੇਂ", "ਹੈ"],
                               ["ਹਸਪਤਾਲ ਕਿੱਥੇ ਹੈ?"],
                               "The pattern is place + ਕਿੱਥੇ + ਹੈ."),
                            mp([("ਨੇੜੇ (nerhe)", "Near"), ("ਦੂਰ (door)", "Far"), ("ਸੱਜੇ (sajje)", "Right"),
                                ("ਖੱਬੇ (khabbe)", "Left")],
                               "Pair opposites to remember them."),
                            ta("Type this in Punjabi (romanized): “Where is the gurdwara?”",
                               _roman("gurdwara kitthe hai",
                                      ["gurdwara", "gurdwaara", "gurduara", "gurduaara", "gurudwara"],
                                      ["kitthe", "kithe", "kitthey", "kithey"], ["hai", "ae", "e"],
                                      extra=("ਗੁਰਦੁਆਰਾ ਕਿੱਥੇ ਹੈ?",)),
                               "ਗੁਰਦੁਆਰਾ ਕਿੱਥੇ ਹੈ? — place + ਕਿੱਥੇ + ਹੈ.",
                               TYPE_HINT),
                            mc("How do you say “The gurdwara is on the left”?",
                               ["ਗੁਰਦੁਆਰਾ ਸੱਜੇ ਪਾਸੇ ਹੈ (gurdwara sajje paase hai)",
                                "ਗੁਰਦੁਆਰਾ ਖੱਬੇ ਪਾਸੇ ਹੈ (gurdwara khabbe paase hai)",
                                "ਗੁਰਦੁਆਰਾ ਦੂਰ ਹੈ (gurdwara door hai)",
                                "ਗੁਰਦੁਆਰਾ ਕਿੱਥੇ ਹੈ? (gurdwara kitthe hai?)"],
                               "ਗੁਰਦੁਆਰਾ ਖੱਬੇ ਪਾਸੇ ਹੈ (gurdwara khabbe paase hai)",
                               "ਪਾਸੇ means “side”: ਖੱਬੇ ਪਾਸੇ = on the left side, ਸੱਜੇ ਪਾਸੇ = on the right."),
                        ],
                    ),
                ],
            },
        ],
    },
]

COURSE: dict[str, Any] = {
    "title": "Punjabi",
    "language_code": "pa",
    "flag_emoji": "🇮🇳",
    "description": "Learn Gurmukhi Punjabi: greetings, family, food, numbers and getting around town.",
    "units": UNITS,
}
